name       : gdm
version    : 3.32.0
release    : 44
source     :
    - https://download.gnome.org/sources/gdm/3.32/gdm-3.32.0.tar.xz : 643db0c8c5089a96282b4c259b8823ca6dfad1ead6f2d0025d1c1211d36fd78b
homepage   : https://projects.gnome.org/gdm/
license    : GPL-2.0
summary    : GNOME Graphical Display Manager
component  : desktop.gnome
conflicts  :
    - lightdm
    - lightdm-gtk-greeter
    - slick-greeter
description: |
    A graphical login manager for your desktop, integrated within the GNOME desktop environment
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - itstool
rundeps    :
    - gnome-shell
    - linux-driver-management-gdm-integration
    - setxkbmap
    - xauth
    - xhost
    - xkbcomp
    - xkeyboard-config
setup      : |
    %apply_patches
    %configure --disable-static \
               --enable-console-helper \
               --enable-gdm-xsession \
               --enable-introspection \
               --enable-systemd-journal \
               --enable-wayland-support \
               --with-at-spi-registryd-directory=%libdir%/at-spi2/core \
               --with-check-accelerated-directory=%libdir%/gnome-session  \
               --with-dbus-sys=/usr/share/dbus-1/system.d \
               --with-default-pam-config=lfs \
               --with-group="gdm" \
               --with-initial-vt=7 \
               --without-console-kit \
               --without-plymouth \
               --with-pam-mod-dir=/lib/security \
               --with-run-dir=/run/gdm \
               --with-systemd \
               --with-user="gdm"
build      : |
    %make
install    : |
    %make_install

    # Use factory mechanism to ensure GDM config is present
    install -D -m 00644 $pkgfiles/client.conf $installdir/usr/share/factory/var/lib/gdm/.config/pulse/client.conf

    # Ensure we have sysusers + tmpfiles
    install -D -m 00644 $pkgfiles/gdm.sysusers $installdir/%libdir%/sysusers.d/gdm.conf
    install -D -m 00644 $pkgfiles/gdm.tmpfiles $installdir/%libdir%/tmpfiles.d/gdm.conf

    # Pre-enable gdm (gdm forces "lib")
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/graphical.target.wants
    ln -sv ../gdm.service $installdir/usr/lib/systemd/system/graphical.target.wants/gdm.service
    ln -sv gdm.service $installdir/usr/lib/systemd/system/displaymanager.service

    # systemd handled
    rm -rf $installdir/{var,run}

    # fix PAM
    rm -rf $installdir/etc/pam.d
    install -d $installdir/usr/share/defaults/etc/pam.d
    cp $pkgfiles/pam/* $installdir/usr/share/defaults/etc/pam.d/
    chmod 00644 $installdir/usr/share/defaults/etc/pam.d/*
