name       : gdm
version    : '41.3'
release    : 59
source     :
    - https://download.gnome.org/sources/gdm/41/gdm-41.3.tar.xz : bb0b650a7cea90f09a33284fbd02975315407efc18e814009852d1bcad3437d4
homepage   : https://projects.gnome.org/gdm/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Graphical Display Manager
description: |
    A graphical login manager for your desktop, integrated within the GNOME desktop environment
conflicts  :
    - lightdm
    - lightdm-gtk-greeter
    - sddm
    - slick-greeter
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(dconf)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - itstool
rundeps    :
    - gnome-shell
    - linux-driver-management-gdm-integration
    - setxkbmap
    - xauth
    - xhost
    - xkbcomp
    - xkeyboard-config
setup      : |
    %patch -p1 < $pkgfiles/0001-Force-Xorg-use-on-the-login-screen.patch
    %patch -p1 < $pkgfiles/0001-Source-usr-share-defaults-etc-xprofile.patch
    %meson_configure \
        -Dat-spi-registryd-dir=%libdir%/at-spi2/core \
        -Ddbus-sys=/usr/share/dbus-1/system.d \
        -Ddefault-pam-config=lfs \
        -Dgdm-xsession=true \
        -Dpam-mod-dir=/lib/security \
        -Drun-dir=/run/gdm \
        -Dwayland-support=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Use factory mechanism to ensure GDM config is present
    install -D -m 00644 $pkgfiles/client.conf $installdir/usr/share/factory/var/lib/gdm/.config/pulse/client.conf

    # Ensure we have sysusers + tmpfiles
    install -D -m 00644 $pkgfiles/gdm.sysusers $installdir/%libdir%/sysusers.d/gdm.conf
    install -D -m 00644 $pkgfiles/gdm.tmpfiles $installdir/%libdir%/tmpfiles.d/gdm.conf

    # Pre-enable gdm (gdm forces "lib")
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/graphical.target.wants
    ln -sv ../gdm.service $installdir/usr/lib/systemd/system/graphical.target.wants/gdm.service
    ln -sv gdm.service $installdir/usr/lib/systemd/system/displaymanager.service

    # systemd handled
    rm -rf $installdir/{var,run}

    # fix PAM
    rm -rf $installdir/etc/pam.d
    install -d $installdir/usr/share/defaults/etc/pam.d
    cp $pkgfiles/pam/* $installdir/usr/share/defaults/etc/pam.d/
    chmod 00644 $installdir/usr/share/defaults/etc/pam.d/*
